"""initial schema

Revision ID: a72aa462609e
Revises: 
Create Date: 2026-09-07 23:02:56.274813
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a72aa462609e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club'))
    )
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_slug'), ['slug'], unique=True)

    op.create_table('external_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('external_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_id')),
    sa.UniqueConstraint('source', 'entity_type', 'entity_id', name=op.f('uq_external_id_source')),
    sa.UniqueConstraint('source', 'entity_type', 'external_key', name=op.f('uq_external_id_source'))
    )
    with op.batch_alter_table('external_id', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_id_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_id_source'), ['source'], unique=False)

    op.create_table('import_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_run'))
    )
    with op.batch_alter_table('import_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_run_source'), ['source'], unique=False)

    op.create_table('login_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_code'))
    )
    with op.batch_alter_table('login_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_code_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_code_expires_at'), ['expires_at'], unique=False)

    op.create_table('sailor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('federation_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sailor'))
    )
    with op.batch_alter_table('sailor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sailor_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_sailor_federation_id'), ['federation_id'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=48), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('scoring', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series'))
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_series_year'), ['year'], unique=False)

    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('water', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venue'))
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_slug'), ['slug'], unique=True)

    op.create_table('waiver_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('title_de', sa.String(length=200), nullable=False),
    sa.Column('body_de', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waiver_text'))
    )
    with op.batch_alter_table('waiver_text', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiver_text_version'), ['version'], unique=True)

    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name=op.f('fk_app_user_club_id_club')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_email'), ['email'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('boat_count', sa.Integer(), nullable=False),
    sa.Column('flight_count', sa.Integer(), nullable=False),
    sa.Column('crew_size', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('host_club_id', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('sap_leaderboard', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['host_club_id'], ['club.id'], name=op.f('fk_event_host_club_id_club')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_event_series_id_series')),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_event_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    sa.UniqueConstraint('series_id', 'matchday', name=op.f('uq_event_series_id'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_host_club_id'), ['host_club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_venue_id'), ['venue_id'], unique=False)

    op.create_table('boat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=True),
    sa.Column('sail_number', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_boat_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boat')),
    sa.UniqueConstraint('event_id', 'number', name=op.f('uq_boat_event_id'))
    )
    with op.batch_alter_table('boat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boat_event_id'), ['event_id'], unique=False)

    op.create_table('club_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name=op.f('fk_club_member_club_id_club')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_club_member_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_member')),
    sa.UniqueConstraint('club_id', 'user_id', name=op.f('uq_club_member_club_id'))
    )
    with op.batch_alter_table('club_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_member_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_member_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_member_user_id'), ['user_id'], unique=False)

    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_flight_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight')),
    sa.UniqueConstraint('event_id', 'number', name=op.f('uq_flight_event_id'))
    )
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_event_id'), ['event_id'], unique=False)

    op.create_table('identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_identity_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity')),
    sa.UniqueConstraint('provider', 'subject', name=op.f('uq_identity_provider'))
    )
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_user_id'), ['user_id'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('series_id IS NOT NULL OR event_id IS NOT NULL', name=op.f('ck_team_team_hat_einen_wettbewerb')),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name=op.f('fk_team_club_id_club')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_team_event_id_event')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_team_series_id_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team')),
    sa.UniqueConstraint('club_id', 'event_id', name=op.f('uq_team_club_id'))
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_status'), ['status'], unique=False)
        batch_op.create_index('uq_team_series_meldung', ['club_id', 'series_id'], unique=True, sqlite_where=sa.text('event_id IS NULL'), postgresql_where=sa.text('event_id IS NULL'))

    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_role_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('user_id', 'role', name=op.f('uq_user_role_user_id'))
    )
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_user_id'), ['user_id'], unique=False)

    op.create_table('waiver_confirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sailor_id', sa.Integer(), nullable=False),
    sa.Column('waiver_text_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('locale_shown', sa.String(length=2), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('guardian_name', sa.String(length=160), nullable=True),
    sa.Column('guardian_signature_ref', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(series_id IS NULL) <> (event_id IS NULL)', name=op.f('ck_waiver_confirmation_exactly_one_scope')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_waiver_confirmation_event_id_event')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_user.id'], name=op.f('fk_waiver_confirmation_recorded_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['sailor_id'], ['sailor.id'], name=op.f('fk_waiver_confirmation_sailor_id_sailor')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_waiver_confirmation_series_id_series')),
    sa.ForeignKeyConstraint(['waiver_text_id'], ['waiver_text.id'], name=op.f('fk_waiver_confirmation_waiver_text_id_waiver_text')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waiver_confirmation'))
    )
    with op.batch_alter_table('waiver_confirmation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiver_confirmation_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_confirmation_sailor_id'), ['sailor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_confirmation_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_confirmation_waiver_text_id'), ['waiver_text_id'], unique=False)
        batch_op.create_index('uq_waiver_conf_event', ['sailor_id', 'event_id', 'waiver_text_id'], unique=True, sqlite_where=sa.text('series_id IS NULL'), postgresql_where=sa.text('series_id IS NULL'))
        batch_op.create_index('uq_waiver_conf_series', ['sailor_id', 'series_id', 'waiver_text_id'], unique=True, sqlite_where=sa.text('event_id IS NULL'), postgresql_where=sa.text('event_id IS NULL'))

    op.create_table('event_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sailor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_crew_event_id_event')),
    sa.ForeignKeyConstraint(['sailor_id'], ['sailor.id'], name=op.f('fk_event_crew_sailor_id_sailor')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_event_crew_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_crew')),
    sa.UniqueConstraint('event_id', 'sailor_id', name=op.f('uq_event_crew_event_id'))
    )
    with op.batch_alter_table('event_crew', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_crew_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_crew_sailor_id'), ['sailor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_crew_team_id'), ['team_id'], unique=False)

    op.create_table('event_standing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('net_points', sa.Float(), nullable=False),
    sa.Column('races_scored', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_standing_event_id_event')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_event_standing_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_standing')),
    sa.UniqueConstraint('event_id', 'team_id', name=op.f('uq_event_standing_event_id'))
    )
    with op.batch_alter_table('event_standing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_standing_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_standing_team_id'), ['team_id'], unique=False)

    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('number_in_flight', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('fk_race_flight_id_flight')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race')),
    sa.UniqueConstraint('flight_id', 'number_in_flight', name=op.f('uq_race_flight_id'))
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_flight_id'), ['flight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_sequence'), ['sequence'], unique=False)

    op.create_table('series_standing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('events_sailed', sa.Integer(), nullable=False),
    sa.Column('events_missed', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_standing_series_id_series')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_series_standing_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series_standing')),
    sa.UniqueConstraint('series_id', 'team_id', name=op.f('uq_series_standing_series_id'))
    )
    with op.batch_alter_table('series_standing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_standing_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_standing_team_id'), ['team_id'], unique=False)

    op.create_table('team_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sailor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sailor_id'], ['sailor.id'], name=op.f('fk_team_membership_sailor_id_sailor')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_membership_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_membership'))
    )
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_membership_sailor_id'), ['sailor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_membership_team_id'), ['team_id'], unique=False)

    op.create_table('race_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('boat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('redress_points', sa.Float(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('is_discarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boat.id'], name=op.f('fk_race_entry_boat_id_boat')),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name=op.f('fk_race_entry_race_id_race')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_race_entry_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_entry')),
    sa.UniqueConstraint('race_id', 'boat_id', name=op.f('uq_race_entry_race_id')),
    sa.UniqueConstraint('race_id', 'team_id', name=op.f('uq_race_entry_race_id'))
    )
    with op.batch_alter_table('race_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_entry_boat_id'), ['boat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_entry_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_entry_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_entry_team_id'))
        batch_op.drop_index(batch_op.f('ix_race_entry_race_id'))
        batch_op.drop_index(batch_op.f('ix_race_entry_boat_id'))

    op.drop_table('race_entry')
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_membership_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_membership_sailor_id'))

    op.drop_table('team_membership')
    with op.batch_alter_table('series_standing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_standing_team_id'))
        batch_op.drop_index(batch_op.f('ix_series_standing_series_id'))

    op.drop_table('series_standing')
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_sequence'))
        batch_op.drop_index(batch_op.f('ix_race_flight_id'))

    op.drop_table('race')
    with op.batch_alter_table('event_standing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_standing_team_id'))
        batch_op.drop_index(batch_op.f('ix_event_standing_event_id'))

    op.drop_table('event_standing')
    with op.batch_alter_table('event_crew', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_crew_team_id'))
        batch_op.drop_index(batch_op.f('ix_event_crew_sailor_id'))
        batch_op.drop_index(batch_op.f('ix_event_crew_event_id'))

    op.drop_table('event_crew')
    with op.batch_alter_table('waiver_confirmation', schema=None) as batch_op:
        batch_op.drop_index('uq_waiver_conf_series', sqlite_where=sa.text('event_id IS NULL'), postgresql_where=sa.text('event_id IS NULL'))
        batch_op.drop_index('uq_waiver_conf_event', sqlite_where=sa.text('series_id IS NULL'), postgresql_where=sa.text('series_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_waiver_confirmation_waiver_text_id'))
        batch_op.drop_index(batch_op.f('ix_waiver_confirmation_series_id'))
        batch_op.drop_index(batch_op.f('ix_waiver_confirmation_sailor_id'))
        batch_op.drop_index(batch_op.f('ix_waiver_confirmation_event_id'))

    op.drop_table('waiver_confirmation')
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_role_role'))

    op.drop_table('user_role')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('uq_team_series_meldung', sqlite_where=sa.text('event_id IS NULL'), postgresql_where=sa.text('event_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_team_status'))
        batch_op.drop_index(batch_op.f('ix_team_series_id'))
        batch_op.drop_index(batch_op.f('ix_team_event_id'))
        batch_op.drop_index(batch_op.f('ix_team_club_id'))

    op.drop_table('team')
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_user_id'))
        batch_op.drop_index(batch_op.f('ix_identity_provider'))

    op.drop_table('identity')
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_event_id'))

    op.drop_table('flight')
    with op.batch_alter_table('club_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_club_member_status'))
        batch_op.drop_index(batch_op.f('ix_club_member_club_id'))

    op.drop_table('club_member')
    with op.batch_alter_table('boat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boat_event_id'))

    op.drop_table('boat')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_venue_id'))
        batch_op.drop_index(batch_op.f('ix_event_slug'))
        batch_op.drop_index(batch_op.f('ix_event_series_id'))
        batch_op.drop_index(batch_op.f('ix_event_host_club_id'))

    op.drop_table('event')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_email'))
        batch_op.drop_index(batch_op.f('ix_app_user_club_id'))

    op.drop_table('app_user')
    with op.batch_alter_table('waiver_text', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiver_text_version'))

    op.drop_table('waiver_text')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_slug'))

    op.drop_table('venue')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_year'))
        batch_op.drop_index(batch_op.f('ix_series_slug'))

    op.drop_table('series')
    with op.batch_alter_table('sailor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sailor_federation_id'))
        batch_op.drop_index(batch_op.f('ix_sailor_email'))

    op.drop_table('sailor')
    with op.batch_alter_table('login_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_code_expires_at'))
        batch_op.drop_index(batch_op.f('ix_login_code_email'))

    op.drop_table('login_code')
    with op.batch_alter_table('import_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_run_source'))

    op.drop_table('import_run')
    with op.batch_alter_table('external_id', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_id_source'))
        batch_op.drop_index(batch_op.f('ix_external_id_entity_id'))

    op.drop_table('external_id')
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_slug'))

    op.drop_table('club')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
