import { readFileSync } from "node:fs";

import { test as base } from "@playwright/test";
import * as allure from "allure-js-commons";

/** The `test` every spec here imports — Playwright's, pointed at this worker's own stack.
 *
 * The suite used to run on one worker because every spec talks to one database and
 * `lifecycle.spec.ts` writes to it: run two at once and a test reads a list while another
 * is changing it. Ordering those writes is not possible and not the point — the fix is to
 * stop sharing the data. `scripts/dev-stack.sh --workers N` runs N stacks, each with its
 * own SQLite file, and this hands worker *i* the *i*-th of them.
 *
 * `baseURL` is an option fixture, which is why this works at all: a worker cannot change
 * `use.baseURL` in the config, but it can override the fixture that provides it, and every
 * spec navigates with relative paths.
 */
export const test = base.extend<{ allureNoStory: void }, { stackBaseURL: string }>({
  // A test in no story group ("Foundations") lands in Allure's "(no story)" group, the
  // same one the backend's story-less tests go to — rather than loose at the report's root.
  allureNoStory: [
    async ({}, use, testInfo) => {
      if (!testInfo.tags.some((tag) => /^@[A-Z]+-\d+$/.test(tag))) {
        await allure.story("(no story)");
      }
      await use();
    },
    { auto: true },
  ],
  // Worker-scoped: computed once per worker rather than per test.
  stackBaseURL: [
    async ({}, use, workerInfo) => {
      // `parallelIndex`, **not** `workerIndex`. `workerIndex` counts every worker the run
      // has ever started and keeps climbing as workers are replaced after a failure — it
      // reached 5187 here, addressing servers that were never started. `parallelIndex` is
      // the slot, 0 .. workers-1, which is what "the n-th stack" means.
      await use(`http://127.0.0.1:${5173 + workerInfo.parallelIndex}`);
    },
    { scope: "worker" },
  ],
  baseURL: async ({ stackBaseURL }, use) => {
    await use(stackBaseURL);
  },
});

export { expect } from "@playwright/test";

/** Every story's title and place, generated by `scripts/check-docs.py --fix`. */
const STORIES: Record<string, { title: string; role: string; phase: string; file: string; anchor: string }> =
  JSON.parse(readFileSync(new URL("../docs/stories.json", import.meta.url), "utf-8"));
const REPOSITORY = "https://github.com/gundramleifert/segel-bundesliga/blob/main";

/** Labels each test of a group for Allure (evidence mode writes `allure-results/`): each
 * story, its role and its phase — the same labels the backend tests get from
 * `api/tests/conftest.py`. Without the Allure reporter these calls do nothing. */
function labelStories(ids: string[]): void {
  test.beforeEach(async () => {
    for (const id of ids) {
      const story = STORIES[id];
      if (!story) continue;
      await allure.epic(story.role);
      await allure.feature(story.phase);
      await allure.story(`${id} · ${story.title}`);
      await allure.tag(id);
      await allure.link(`${REPOSITORY}/${story.file}#${story.anchor}`, id);
    }
  });
}

/** The story IDs at the start of a describe title: "VA-8/VA-9: from a draft …". */
const STORY_TITLE = /^([A-Z]+-\d+(?:\/[A-Z]+-\d+)*): /;

/** `test.describe` for a group of tests that covers user stories — tagged with them.
 *
 * The title stays the one place a spec names its stories, as it always did; this turns
 * those IDs into Playwright tags (`@VA-8`, `@VA-9`). The HTML report then filters by story
 * (one click on a tag), `--grep @VA-8` runs one story's tests, and the evidence report
 * (`EVIDENCE=1`) shows each story's videos together. A title without IDs is refused
 * rather than quietly left untagged, and `scripts/check-docs.py` checks every ID is a
 * real story. A group that covers no story ("Foundations") uses plain `test.describe`.
 */
export function describeStory(title: string, body: () => void): void {
  const match = STORY_TITLE.exec(title);
  if (!match) {
    throw new Error(`describeStory: "${title}" must start with its story IDs, e.g. "VA-8/VA-9: …"`);
  }
  const ids = match[1].split("/");
  test.describe(title, { tag: ids.map((id) => `@${id}`) }, () => {
    labelStories(ids);
    body();
  });
}

/** `test.describe` for a **journey** (`docs/userstories/journeys.md`): several stories in
 * the order they really happen, walked by one long test.
 *
 * Tagged `@J-1` like a story group, so the report and `--grep "@J-1\b"` find it. Inside it,
 * every stretch of the walk is a `step()`, and `scripts/check-docs.py` checks that those
 * steps are the journey's numbered main steps, in order.
 */
export function describeJourney(title: string, body: () => void): void {
  const match = /^(J-\d+): /.exec(title);
  if (!match) {
    throw new Error(`describeJourney: "${title}" must start with its journey ID, e.g. "J-1: …"`);
  }
  test.describe(title, { tag: [`@${match[1]}`] }, () => {
    labelStories([match[1]]);
    body();
  });
}

/** One step of a journey: the story it walks through, and what happens in it.
 *
 * Playwright's `test.step` underneath, titled "VA-7: organizer draws the pairing list" —
 * so the step is a chapter of the trace (evidence mode, `EVIDENCE=1`) and a failure names
 * the step it happened in. The story is also recorded as an annotation, which puts it in
 * the HTML report beside the test.
 */
export async function step<T>(story: string, what: string, body: () => Promise<T>): Promise<T> {
  if (!/^[A-Z]+-\d+$/.test(story)) {
    throw new Error(`step: "${story}" is not a story ID, e.g. "VA-7"`);
  }
  test.info().annotations.push({ type: "story", description: story });
  return test.step(`${story}: ${what}`, body);
}
