import os

from pydantic_settings import BaseSettings, SettingsConfigDict

# Render (and Docker Secrets, Kubernetes) mount uploaded secret files here, one file per
# secret, named exactly like the env var it replaces (e.g. a file literally named
# "SBL_JWT_SECRET"). pydantic-settings reads it under that name automatically — this is
# the mechanism, not a convention invented here. Used only for the fields that are
# genuine credentials (jwt_secret, smtp_password); everything else stays a plain,
# non-sensitive env var — see docs/deploy.md. An explicit env var still wins if both are
# set, and fields fall back to their defaults if the file is absent (e.g. local
# development, where the directory itself usually doesn't exist at all). Guarded on
# existence purely to skip pydantic-settings' otherwise-harmless "directory does not
# exist" warning locally.
_SECRETS_DIR = "/etc/secrets" if os.path.isdir("/etc/secrets") else None


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env", env_prefix="SBL_", extra="ignore", secrets_dir=_SECRETS_DIR
    )

    # SQLite — a file next to the code, no server to start first. For the data volumes of a
    # league this is more than sufficient; Postgres remains the goal once it goes into
    # production. Therefore Postgres-specific types (JSONB, ARRAY) stay out of the model,
    # and Alembic runs in batch mode for SQLite.
    database_url: str = "sqlite+aiosqlite:///./sbl.db"
    cors_origins: list[str] = ["http://localhost:5173"]
    debug: bool = True

    # Where runtime uploads (sailor photos, club crests, ...) are stored on local disk. A
    # file's mere existence at a deterministic path (e.g. "sailors/{sailor_id}.jpg",
    # "clubs/{club_id}.png") *is* the "has an image" state — no database column needed.
    # Not versioned (see .gitignore); an S3-compatible store remains a future option, see
    # docs/userstories.md, Stories S-2 and V-3.
    uploads_dir: str = "uploads"

    # Pairing lists are generated by the existing Java tool (reference/PairingList) for now.
    # It optimizes boat swaps and shuttle runs, which the native Python generator cannot do yet
    # — see docs/findings.md, section 2.
    pairing_jar: str = (
        "../reference/PairingList/target/"
        "pairing-list-1.0-SNAPSHOT-jar-with-dependencies.jar"
    )
    java_binary: str = "java"
    # A full run with production configuration takes many minutes.
    pairing_timeout_seconds: int = 1800

    # Signature for access tokens. Empty means: no tokens are issued and none accepted
    # — the protected area is closed, not open.
    jwt_secret: str = ""
    jwt_lifetime_minutes: int = 720

    # Development aid: issues access tokens without verification (app/routers/dev.py).
    # Intentionally a separate setting and not tied to debug — it must never be active
    # accidentally in a reachable environment.
    dev_login: bool = False

    # Identity providers. Without a registered application ID, the respective path is closed.
    google_client_id: str = ""
    microsoft_client_id: str = ""
    microsoft_tenant: str = "common"

    # One-time code via email
    otp_length: int = 6
    otp_lifetime_minutes: int = 10
    otp_max_attempts: int = 5

    # Accounts normally arise through creation or import, not through login.
    # This affects the **implicit** creation when logging in with an unknown address
    # — not explicit registration.
    allow_self_signup: bool = False
    # Whether someone can register themselves (POST /api/auth/register). An account created
    # this way has no role and no club: it can only request admission to a club. Everything
    # else depends on this admission.
    allow_registration: bool = True

    # Addresses that automatically become `admin` the moment they successfully sign in
    # (any provider) — a fresh deployment otherwise has no admin at all and nothing else
    # in the interface can grant that first role. Compared case-insensitively; harmless to
    # list the same address after it already has the role (see app.services.login).
    admin_emails: list[str] = []

    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_password: str = ""
    # Two different ways providers expect encryption on the wire — not interchangeable:
    # STARTTLS upgrades a plaintext connection (typically port 587/25); implicit TLS/SSL
    # encrypts from the first byte (typically port 465). STRATO, for example, documents
    # 465/SSL as the path for normal mail clients and 587/STARTTLS as relay-only — check
    # your provider's docs rather than assuming. smtp_ssl wins if both were set.
    smtp_starttls: bool = True
    smtp_ssl: bool = False
    mail_from: str = "noreply@segelbundesliga.de"

    # Alternate transport for hosts that block outbound SMTP entirely (confirmed on the
    # Render test deployment — both port 465 and 587 time out; see docs/deploy.md). Sends
    # over Brevo's HTTPS API instead of smtplib when set; SMTP above stays the intended
    # path for a real host that can reach an SMTP server. Opt-in and dev/test-only — not a
    # replacement for SMTP, a workaround for one platform's egress firewall.
    brevo_api_key: str = ""


settings = Settings()
