from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_prefix="SBL_", extra="ignore")

    # SQLite — a file next to the code, no server to start first. For the data volumes of a
    # league this is more than sufficient; Postgres remains the goal once it goes into
    # production. Therefore Postgres-specific types (JSONB, ARRAY) stay out of the model,
    # and Alembic runs in batch mode for SQLite.
    database_url: str = "sqlite+aiosqlite:///./sbl.db"
    cors_origins: list[str] = ["http://localhost:5173"]
    debug: bool = True

    # Pairing lists are generated by the existing Java tool (reference/PairingList) for now.
    # It optimizes boat swaps and shuttle runs, which the native Python generator cannot do yet
    # — see docs/findings.md, section 2.
    pairing_jar: str = (
        "../reference/PairingList/target/"
        "pairing-list-1.0-SNAPSHOT-jar-with-dependencies.jar"
    )
    java_binary: str = "java"
    # A full run with production configuration takes many minutes.
    pairing_timeout_seconds: int = 1800

    # Signature for access tokens. Empty means: no tokens are issued and none accepted
    # — the protected area is closed, not open.
    jwt_secret: str = ""
    jwt_lifetime_minutes: int = 720

    # Development aid: issues access tokens without verification (app/routers/dev.py).
    # Intentionally a separate setting and not tied to debug — it must never be active
    # accidentally in a reachable environment.
    dev_login: bool = False

    # Identity providers. Without a registered application ID, the respective path is closed.
    google_client_id: str = ""
    microsoft_client_id: str = ""
    microsoft_tenant: str = "common"

    # One-time code via email
    otp_length: int = 6
    otp_lifetime_minutes: int = 10
    otp_max_attempts: int = 5

    # Accounts normally arise through creation or import, not through login.
    # This affects the **implicit** creation when logging in with an unknown address
    # — not explicit registration.
    allow_self_signup: bool = False
    # Whether someone can register themselves (POST /api/auth/register). An account created
    # this way has no role and no club: it can only request admission to a club. Everything
    # else depends on this admission.
    allow_registration: bool = True

    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_password: str = ""
    smtp_starttls: bool = True
    mail_from: str = "noreply@segelbundesliga.de"


settings = Settings()
