"""Request and response models for administrative endpoints."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class PairingJobRequest(BaseModel):
    """Job to calculate a pairing list (Story VA-3)."""

    flights: int = Field(default=16, ge=1, le=40)
    boats: int = Field(default=6, ge=2, le=20)
    seed: int = Field(default=1240, description="Makes the draw reproducible")
    effort: Literal["fast", "full"] = Field(
        default="full",
        description=(
            "'full' matches the setting for real matchdays and runs for many minutes. "
            "'fast' delivers a usable but poorer list in seconds."
        ),
    )


class JobOut(BaseModel):
    id: str
    kind: str
    status: str
    progress: float
    message: str
    error: str | None = None
    created_at: datetime
    finished_at: datetime | None = None
    # For completed pairing calculation the quality report, otherwise empty.
    quality: dict[str, Any] = Field(default_factory=dict)


class PairingImportRequest(BaseModel):
    """Import a list created elsewhere — for example from the Java tool."""

    schedule_config: str = Field(description="Content of schedule_cfg.yml")
    pairing_list: str = Field(description="Content of pairing_list.yml")


class PublishRequest(BaseModel):
    job_id: str


class PublishResult(BaseModel):
    boats: int
    flights: int
    races: int
    entries: int
    quality: dict[str, Any] = Field(default_factory=dict)


class RaceResultIn(BaseModel):
    """A result as recorded by the race officer."""

    boat_number: int
    code: str
    finish_position: int | None = None
    redress_points: float | None = None


class RaceResultsIn(BaseModel):
    results: list[RaceResultIn]
    # Version on which the entry is based. If it differs, someone else has changed it
    # in the meantime — the later entry wins, the discarded one is logged.
    version: int | None = None
    idempotency_key: str | None = Field(
        default=None,
        description="Generated by the device; prevents double entries when submitting late.",
    )


class RaceResultsOut(BaseModel):
    race_id: int
    sequence: int
    status: str
    version: int
    applied: bool
    overwrote_existing: bool = False
    note: str | None = None
